---
version: '3'
services:
  bastion:
    container_name: bastion
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ${home_directory:-/home}:/home/:${home_directory_ro:-ro}
      - ${passwd_filename:-/etc/passwd}:/etc/passwd:${passwd_filename_ro:-ro}
      - ${shadow_filename:-/etc/shadow}:/etc/shadow:${shadow_filename_ro:-ro}
      - ${group_filename:-/etc/group}:/etc/group:${group_filename_ro:-ro}
      - ${timezone_filename:-/etc/timezone}:/etc/timezone:${timezone_filename_ro:-ro}
      - ssh_host_keys:/etc/ssl/private/sshd/
    restart: unless-stopped
    network_mode: host
    entrypoint: ["/entrypoint.sh"]
    command: ["-D", "-e"]
    environment:
      - port=${port:-22}
      - allow_users=${allow_users:-}
    logging:
      driver: "json-file"
      options:
        max-size: 100m
volumes:
  ssh_host_keys:
