---
name: Run tests

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
  push:

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build:
    name: Build Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          push: false
          tags: test-image:latest

      - uses: addnab/docker-run-action@v3
        with:
        image: test-image:latest
        run: "-t"
